### ISSUE TITLE
Why use dev mode on the frontend in production

### ISSUE THREAD

**Issue by SoneNiko** [evroon/bracket#441]
the docker compose stack specifies to use the following env var in prod "ENVIRONMENT=DEVELOPMENT".

is there any specific reason for it? I would like to not do that because its not advised to run nextjs in that way in production

**Comment by evroon** [comment]
Ah thank I didn't think of that, I don't run Bracket in production using Docker but as systemd service. 
I have updated the docs to include a docker-compose.yml that is more suitable for production: https://evroon.github.io/bracket/docs/running-bracket/deployment#docker

do you have more suggestions for that page? It's quite hard to write documentation explaining something myself as for me everything seems more straightforward than it actually is because I'm very close to the project.

**Comment by evroon** [comment]
I will close this for now, let me know if there's more to improve here
